#!/bin/bash
cleanup () {
    docker-compose -f test/docker-compose.test.yaml rm -svf
}
trap cleanup EXIT

docker-compose -f test/docker-compose.test.yaml run --rm --name=${IMAGEBASE}-api-${GIT_HASH} test-api
docker-compose -f test/docker-compose.test.yaml run --rm --name=${IMAGEBASE}-bot-${GIT_HASH} test-bot
